version: '3.8'

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/astachni/data/html

  mdb:
    driver: local
    name: mdb
    driver_opts:
      type: none
      o: bind
      device: /home/astachni/data/mariadb

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mdb:/var/lib/mysql
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
      - mdb:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped